### ISSUE TITLE
Add Badge for License in README.md

### ISSUE THREAD

**Issue by nikhilkanta** [vrook-co/oto-helper#42]
Check this out for badges. 

[https://github.com/Naereen/badges](https://github.com/Naereen/badges)

**Comment by mathagician** [comment]
Hello @nikhilkanta. Could you please tell which licence and also add hacktober fest tag.

**Comment by mathagician** [comment]
Please assign this to me

**Comment by nikhilkanta** [comment]
Yes, You can have this!

**Comment by mathagician** [comment]
I have done it.
